-- ============================================================
-- Eify 数据库初始化脚本（PostgreSQL 17，最终态）
-- 由 Flyway 自动执行
-- 由 MySQL V1 + V4~V7 增量折叠而成，并合并 document_chunk 向量表
-- ============================================================
--
-- 表清单（按模块分组）：
--   用户与工作空间：ai_user, ai_workspace, ai_workspace_member, ai_workspace_invite, ai_user_session
--   Provider：       provider, model_config, provider_health
--   Agent：          ai_agent
--   Chat：           ai_chat_session, ai_chat_message
--   Knowledge：      knowledge_base, document, agent_knowledge
--   MCP：            mcp_server, mcp_tool, agent_mcp_tool
--   Workflow：       ai_workflow, ai_workflow_node, ai_workflow_edge, ai_workflow_execution
--   向量：           document_chunk
--
-- 规范来源：docs/guides/DATABASE.md, docs/guides/AUTH-WORKSPACE.md
-- ============================================================

CREATE EXTENSION IF NOT EXISTS vector;

-- ############################################################
-- 1. 用户与工作空间模块
-- ############################################################

-- 用户表
CREATE TABLE IF NOT EXISTS ai_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(64)   NOT NULL,
    email         VARCHAR(128)  NOT NULL DEFAULT '',
    password      VARCHAR(256)  NOT NULL,
    display_name  VARCHAR(128),
    avatar_url    VARCHAR(512),
    status        SMALLINT      NOT NULL DEFAULT 1,
    last_login_at TIMESTAMPTZ,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    deleted       SMALLINT      NOT NULL DEFAULT 0,
    creator_id    BIGINT,
    CONSTRAINT uk_username UNIQUE (username),
    CONSTRAINT uk_email UNIQUE (email)
);

-- 工作空间表
CREATE TABLE IF NOT EXISTS ai_workspace (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(128) NOT NULL,
    description VARCHAR(512),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted     SMALLINT     NOT NULL DEFAULT 0,
    creator_id  BIGINT       NOT NULL DEFAULT 0
);

-- 工作空间成员表
CREATE TABLE IF NOT EXISTS ai_workspace_member (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT      NOT NULL,
    user_id      BIGINT      NOT NULL,
    role         VARCHAR(32) NOT NULL DEFAULT 'member',
    joined_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted      SMALLINT    NOT NULL DEFAULT 0,
    creator_id   BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT uk_workspace_user UNIQUE (workspace_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_ai_workspace_member_user_id ON ai_workspace_member(user_id);

-- 工作空间邀请码表
CREATE TABLE IF NOT EXISTS ai_workspace_invite (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT      NOT NULL,
    code         VARCHAR(16) NOT NULL,
    expires_at   TIMESTAMPTZ,
    max_uses     INT         NOT NULL DEFAULT 0,
    use_count    INT         NOT NULL DEFAULT 0,
    enabled      SMALLINT    NOT NULL DEFAULT 1,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted      SMALLINT    NOT NULL DEFAULT 0,
    creator_id   BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT uk_code UNIQUE (code)
);
CREATE INDEX IF NOT EXISTS idx_ai_workspace_invite_workspace_id ON ai_workspace_invite(workspace_id);

-- 用户会话表（refresh token 持久化）
CREATE TABLE IF NOT EXISTS ai_user_session (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL,
    refresh_token VARCHAR(256) NOT NULL,
    expires_at    TIMESTAMPTZ  NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_user_session_user_id ON ai_user_session(user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_token ON ai_user_session(refresh_token);

-- ############################################################
-- 2. Provider 模块
-- ############################################################

-- 模型供应商表
CREATE TABLE IF NOT EXISTS provider (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT       NOT NULL DEFAULT 1,
    name         VARCHAR(100) NOT NULL,
    type         VARCHAR(50)  NOT NULL,
    base_url     VARCHAR(500) NOT NULL,
    auth_config  JSONB        NOT NULL,
    enabled      SMALLINT     NOT NULL DEFAULT 1,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted      SMALLINT     NOT NULL DEFAULT 0,
    creator_id   BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_provider_name_workspace_deleted UNIQUE (name, workspace_id, deleted)
);
CREATE INDEX IF NOT EXISTS idx_provider_type_enabled ON provider(type, enabled);
CREATE INDEX IF NOT EXISTS idx_provider_deleted ON provider(deleted);

-- 模型配置表
CREATE TABLE IF NOT EXISTS model_config (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id    BIGINT       NOT NULL,
    name           VARCHAR(100) NOT NULL,
    model_id       VARCHAR(100) NOT NULL,
    model_category SMALLINT     NOT NULL DEFAULT 0,
    context_size   INT          NOT NULL DEFAULT 0,
    extra_params   JSONB        NOT NULL,
    enabled        SMALLINT     NOT NULL DEFAULT 1,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted        SMALLINT     NOT NULL DEFAULT 0,
    creator_id     BIGINT       NOT NULL DEFAULT 0,
    workspace_id   BIGINT       NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS idx_model_config_provider_id ON model_config(provider_id);
CREATE INDEX IF NOT EXISTS idx_model_config_model_id ON model_config(model_id);
CREATE INDEX IF NOT EXISTS idx_model_config_enabled_deleted ON model_config(enabled, deleted);
CREATE INDEX IF NOT EXISTS idx_model_category ON model_config(model_category);

-- 供应商健康状态表
CREATE TABLE IF NOT EXISTS provider_health (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id     BIGINT       NOT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'UNKNOWN',
    last_check_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    last_success_at TIMESTAMPTZ,
    fail_count      INT          NOT NULL DEFAULT 0,
    latency_ms      INT,
    error_message   VARCHAR(500),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted         SMALLINT     NOT NULL DEFAULT 0,
    creator_id      BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_provider_id UNIQUE (provider_id)
);

-- ############################################################
-- 3. Agent 模块
-- ############################################################

-- Agent 配置表
CREATE TABLE IF NOT EXISTS ai_agent (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id        BIGINT        NOT NULL DEFAULT 1,
    name                VARCHAR(100)  NOT NULL,
    description         VARCHAR(500),
    avatar              VARCHAR(500),
    default_provider_id BIGINT        NOT NULL,
    default_model       VARCHAR(100)  NOT NULL,
    system_prompt       TEXT          NOT NULL,
    user_message_prefix VARCHAR(1000),
    welcome_message     VARCHAR(500),
    temperature         NUMERIC(3,2)  NOT NULL DEFAULT 0.70,
    max_tokens          INT           NOT NULL DEFAULT 2000,
    top_p               NUMERIC(3,2)  NOT NULL DEFAULT 1.00,
    frequency_penalty   NUMERIC(3,2)  NOT NULL DEFAULT 0.00,
    presence_penalty    NUMERIC(3,2)  NOT NULL DEFAULT 0.00,
    max_history_rounds  INT           NOT NULL DEFAULT 10,
    stream_enabled      SMALLINT      NOT NULL DEFAULT 1,
    workflow_id         BIGINT,
    rag_enabled         SMALLINT      NOT NULL DEFAULT 0,
    rag_top_k           INT           NOT NULL DEFAULT 5,
    rag_strategy        VARCHAR(20)   NOT NULL DEFAULT 'hybrid',
    agent_config        JSONB,
    enabled             SMALLINT      NOT NULL DEFAULT 1,
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    deleted             SMALLINT      NOT NULL DEFAULT 0,
    creator_id          BIGINT,
    CONSTRAINT uk_agent_name_workspace_deleted UNIQUE (name, workspace_id, deleted)
);
CREATE INDEX IF NOT EXISTS idx_ai_agent_default_provider_id ON ai_agent(default_provider_id);
CREATE INDEX IF NOT EXISTS idx_ai_agent_enabled_deleted ON ai_agent(enabled, deleted);
CREATE INDEX IF NOT EXISTS idx_ai_agent_created_at ON ai_agent(created_at);
CREATE INDEX IF NOT EXISTS idx_ai_agent_workspace_id ON ai_agent(workspace_id);

-- ############################################################
-- 4. Chat 模块
-- ############################################################

-- 对话会话表
CREATE TABLE IF NOT EXISTS ai_chat_session (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT       NOT NULL DEFAULT 1,
    user_id      BIGINT       NOT NULL,
    agent_id     BIGINT,
    title        VARCHAR(200) NOT NULL,
    status       SMALLINT     NOT NULL DEFAULT 1,
    workflow_id  BIGINT,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted      SMALLINT     NOT NULL DEFAULT 0,
    creator_id   BIGINT       NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_ai_chat_session_user_status_updated_id ON ai_chat_session(user_id, status, updated_at, id);
CREATE INDEX IF NOT EXISTS idx_ai_chat_session_agent_updated_id ON ai_chat_session(agent_id, updated_at, id);
CREATE INDEX IF NOT EXISTS idx_ai_chat_session_created_at ON ai_chat_session(created_at);
CREATE INDEX IF NOT EXISTS idx_ai_chat_session_workspace_id ON ai_chat_session(workspace_id);

-- 聊天消息表（大表，使用游标分页）
CREATE TABLE IF NOT EXISTS ai_chat_message (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   BIGINT      NOT NULL,
    workspace_id BIGINT      NOT NULL,
    role         VARCHAR(20) NOT NULL,
    content      TEXT        NOT NULL,
    token_count  INT         NOT NULL DEFAULT 0,
    model_id     BIGINT,
    metadata     JSONB,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted      SMALLINT    NOT NULL DEFAULT 0,
    creator_id   BIGINT      NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_ai_chat_message_session_id_id ON ai_chat_message(session_id, id);
CREATE INDEX IF NOT EXISTS idx_ai_chat_message_created_at ON ai_chat_message(created_at);
CREATE INDEX IF NOT EXISTS idx_ai_chat_message_session_id_id_role_time ON ai_chat_message(session_id, id, role, created_at);
CREATE INDEX IF NOT EXISTS idx_ai_chat_message_created_at_id ON ai_chat_message(created_at, id);
CREATE INDEX IF NOT EXISTS idx_ai_chat_message_session_workspace_id ON ai_chat_message(session_id, workspace_id, id);

-- ############################################################
-- 5. Knowledge 模块
-- ############################################################

-- 知识库表
CREATE TABLE IF NOT EXISTS knowledge_base (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id       BIGINT       NOT NULL DEFAULT 1,
    name               VARCHAR(100) NOT NULL,
    description        VARCHAR(500),
    embedding_model    VARCHAR(100) NOT NULL DEFAULT 'text-embedding-3-small',
    embedding_model_id BIGINT,
    vector_dimension   INT          NOT NULL DEFAULT 1536,
    chunk_size         INT          NOT NULL DEFAULT 500,
    chunk_overlap      INT          NOT NULL DEFAULT 50,
    document_count     INT          NOT NULL DEFAULT 0,
    chunk_count        INT          NOT NULL DEFAULT 0,
    retrieval_count    INT          NOT NULL DEFAULT 0,
    enabled            SMALLINT     NOT NULL DEFAULT 1,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted            SMALLINT     NOT NULL DEFAULT 0,
    creator_id         BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_knowledge_base_name_workspace_deleted UNIQUE (name, workspace_id, deleted)
);
CREATE INDEX IF NOT EXISTS idx_knowledge_base_enabled ON knowledge_base(enabled);
CREATE INDEX IF NOT EXISTS idx_knowledge_base_deleted ON knowledge_base(deleted);
CREATE INDEX IF NOT EXISTS idx_knowledge_base_workspace_id ON knowledge_base(workspace_id);
CREATE INDEX IF NOT EXISTS idx_embedding_model_id ON knowledge_base(embedding_model_id);

-- 文档表
CREATE TABLE IF NOT EXISTS document (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id   BIGINT       NOT NULL DEFAULT 0,
    knowledge_id   BIGINT       NOT NULL,
    file_name      VARCHAR(255) NOT NULL,
    original_name  VARCHAR(255) NOT NULL,
    file_type      VARCHAR(20)  NOT NULL,
    file_size      BIGINT       NOT NULL,
    file_path      VARCHAR(500) NOT NULL,
    char_count     INT          NOT NULL DEFAULT 0,
    chunk_count    INT          NOT NULL DEFAULT 0,
    process_status SMALLINT     NOT NULL DEFAULT 0,
    error_message  VARCHAR(500),
    enabled        SMALLINT     NOT NULL DEFAULT 1,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted        SMALLINT     NOT NULL DEFAULT 0,
    creator_id     BIGINT       NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_document_workspace ON document(workspace_id);
CREATE INDEX IF NOT EXISTS idx_document_knowledge ON document(knowledge_id);
CREATE INDEX IF NOT EXISTS idx_document_status ON document(process_status);
CREATE INDEX IF NOT EXISTS idx_document_deleted ON document(deleted);

-- Agent 与知识库关联表
CREATE TABLE IF NOT EXISTS agent_knowledge (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id     BIGINT      NOT NULL,
    knowledge_id BIGINT      NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted      SMALLINT    NOT NULL DEFAULT 0,
    creator_id   BIGINT,
    CONSTRAINT uk_agent_knowledge UNIQUE (agent_id, knowledge_id)
);
CREATE INDEX IF NOT EXISTS idx_agent_knowledge_agent_id ON agent_knowledge(agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_knowledge_knowledge_id ON agent_knowledge(knowledge_id);

-- ############################################################
-- 6. MCP 模块
-- ############################################################

-- MCP 服务器表
CREATE TABLE IF NOT EXISTS mcp_server (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(100) NOT NULL,
    description  VARCHAR(500),
    endpoint     VARCHAR(500) NOT NULL,
    enabled      SMALLINT     NOT NULL DEFAULT 1,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted      SMALLINT     NOT NULL DEFAULT 0,
    creator_id   BIGINT       NOT NULL DEFAULT 0,
    workspace_id BIGINT       NOT NULL DEFAULT 1,
    CONSTRAINT uk_mcp_server_name_workspace_deleted UNIQUE (name, workspace_id, deleted)
);
CREATE INDEX IF NOT EXISTS idx_mcp_server_deleted ON mcp_server(deleted);
CREATE INDEX IF NOT EXISTS idx_mcp_server_workspace_id ON mcp_server(workspace_id);

-- MCP 工具表
CREATE TABLE IF NOT EXISTS mcp_tool (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    server_id    BIGINT       NOT NULL,
    name         VARCHAR(200) NOT NULL,
    description  TEXT,
    input_schema JSONB,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted      SMALLINT     NOT NULL DEFAULT 0,
    creator_id   BIGINT       NOT NULL DEFAULT 0,
    workspace_id BIGINT       NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS idx_mcp_tool_server_id ON mcp_tool(server_id);
CREATE INDEX IF NOT EXISTS idx_mcp_tool_deleted ON mcp_tool(deleted);
CREATE INDEX IF NOT EXISTS idx_mcp_tool_workspace_id ON mcp_tool(workspace_id);
CREATE INDEX IF NOT EXISTS idx_mcp_tool_name_workspace ON mcp_tool(name, workspace_id);

-- Agent 绑定的 MCP 工具表
CREATE TABLE IF NOT EXISTS agent_mcp_tool (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id     BIGINT      NOT NULL,
    tool_id      BIGINT      NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted      SMALLINT    NOT NULL DEFAULT 0,
    creator_id   BIGINT      NOT NULL DEFAULT 0,
    workspace_id BIGINT      NOT NULL DEFAULT 1,
    CONSTRAINT uk_agent_tool_workspace UNIQUE (agent_id, tool_id, workspace_id)
);
CREATE INDEX IF NOT EXISTS idx_agent_mcp_tool_agent_id ON agent_mcp_tool(agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_mcp_tool_tool_id ON agent_mcp_tool(tool_id);
CREATE INDEX IF NOT EXISTS idx_agent_mcp_tool_workspace_id ON agent_mcp_tool(workspace_id);

-- ############################################################
-- 7. Workflow 模块
-- ############################################################

-- 工作流主表
CREATE TABLE IF NOT EXISTS ai_workflow (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT       NOT NULL DEFAULT 1,
    name         VARCHAR(100) NOT NULL,
    description  VARCHAR(500),
    status       SMALLINT     NOT NULL DEFAULT 0,
    version      INT          NOT NULL DEFAULT 1,
    variables    JSONB,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted      SMALLINT     NOT NULL DEFAULT 0,
    creator_id   BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_ai_workflow_name_workspace_deleted UNIQUE (name, workspace_id, deleted)
);
CREATE INDEX IF NOT EXISTS idx_ai_workflow_workspace_id ON ai_workflow(workspace_id);
CREATE INDEX IF NOT EXISTS idx_ai_workflow_status ON ai_workflow(status);

-- 工作流节点表
CREATE TABLE IF NOT EXISTS ai_workflow_node (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id BIGINT           NOT NULL,
    node_key    VARCHAR(50)      NOT NULL,
    type        VARCHAR(30)      NOT NULL,
    label       VARCHAR(100),
    position_x  DOUBLE PRECISION,
    position_y  DOUBLE PRECISION,
    config      JSONB,
    created_at  TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
    deleted     SMALLINT         NOT NULL DEFAULT 0,
    creator_id  BIGINT           NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_ai_workflow_node_workflow ON ai_workflow_node(workflow_id);

-- 工作流连线表
CREATE TABLE IF NOT EXISTS ai_workflow_edge (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id    BIGINT      NOT NULL,
    source_node_id BIGINT      NOT NULL,
    target_node_id BIGINT      NOT NULL,
    source_handle  VARCHAR(50) NOT NULL DEFAULT 'default',
    label          VARCHAR(50),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted        SMALLINT    NOT NULL DEFAULT 0,
    creator_id     BIGINT      NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_ai_workflow_edge_workflow ON ai_workflow_edge(workflow_id);
CREATE INDEX IF NOT EXISTS idx_ai_workflow_edge_source ON ai_workflow_edge(source_node_id);

-- 工作流执行记录表
CREATE TABLE IF NOT EXISTS ai_workflow_execution (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id      BIGINT      NOT NULL,
    workflow_version INT,
    status           VARCHAR(20) NOT NULL DEFAULT 'running',
    variables        JSONB,
    current_node_id  BIGINT,
    error_message    TEXT,
    started_at       TIMESTAMPTZ,
    completed_at     TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted          SMALLINT    NOT NULL DEFAULT 0,
    creator_id       BIGINT      NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_ai_workflow_execution_workflow ON ai_workflow_execution(workflow_id);
CREATE INDEX IF NOT EXISTS idx_ai_workflow_execution_status ON ai_workflow_execution(status);

-- ############################################################
-- 8. 向量模块（pgvector）
-- ############################################################

-- 文档分块向量表（embedding 为变长向量，维度由对应知识库决定）
CREATE TABLE IF NOT EXISTS document_chunk (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT      NOT NULL DEFAULT 0,
    knowledge_id BIGINT      NOT NULL,
    document_id  BIGINT      NOT NULL,
    chunk_index  INT         NOT NULL,
    content      TEXT        NOT NULL,
    embedding    VECTOR,
    chunk_hash   CHAR(64)    NOT NULL,
    enabled      SMALLINT    NOT NULL DEFAULT 1,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_chunk_embedding ON document_chunk USING hnsw (embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_chunk_workspace ON document_chunk(workspace_id);
CREATE INDEX IF NOT EXISTS idx_chunk_knowledge ON document_chunk(knowledge_id);
CREATE INDEX IF NOT EXISTS idx_chunk_document ON document_chunk(document_id);
CREATE INDEX IF NOT EXISTS idx_chunk_hash ON document_chunk(chunk_hash);

-- ############################################################
-- 9. 初始数据
-- ############################################################

-- 管理员用户（密码：admin123，BCrypt 加密）
INSERT INTO ai_user (id, username, email, password, display_name, status) VALUES
(1, 'admin', 'admin@eify.local', '$2a$10$CfJnrJ65v1Oyt91xEG/tB.DzgQCLk6gX0reH9LpgHgB6boCapKH3C', 'Admin', 1)
ON CONFLICT (id) DO UPDATE SET password = EXCLUDED.password;

-- 默认工作空间
INSERT INTO ai_workspace (id, name, description) VALUES
(1, 'System Workspace', 'System default workspace')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;

-- 管理员加入默认工作空间
INSERT INTO ai_workspace_member (workspace_id, user_id, role) VALUES
(1, 1, 'owner')
ON CONFLICT (workspace_id, user_id) DO UPDATE SET role = EXCLUDED.role;

-- 同步 IDENTITY 序列（显式插入 id 后序列不会自动前进，用 setval 同步，COALESCE 兜底空表）
SELECT setval(pg_get_serial_sequence('ai_user', 'id'),      COALESCE((SELECT MAX(id) FROM ai_user), 1));
SELECT setval(pg_get_serial_sequence('ai_workspace', 'id'), COALESCE((SELECT MAX(id) FROM ai_workspace), 1));








